### ISSUE TITLE
Raspberry Pi Zero Support

### ISSUE THREAD

**Issue by justbuchanan** [gokrazy/firmware#15]
I have a pi zero and would like to try running gokrazy on it. Any thoughts on how hard it would be to fork this repo and get it to work for the zero? Also, would this likely involve changes to the gokrazy/kernel repo too? Thanks!

**Comment by stapelberg** [comment]
Please see https://www.reddit.com/r/golang/comments/5xgf8u/gokrazy_a_purego_userland_for_your_raspberry_pi_3/dei7b2m/

If you’re still interested in doing this, despite the fact that the changes will most likely not be accepted upstream into gokrazy, what you’d need to do is:

* [ ] change gokrazy to cross-compile for `arm`, not `arm64` (or explicitly set the `GOARCH` environment variable when running `gokr-packer`)
* [ ] change the gokrazy code to work on `arm`. It has only been tested on `arm64`. This includes both compilation failures (I know of parts which won’t even compile on non-64-bit architectures, e.g. `cmd/dhcp`) and runtime failures.
* [ ] fork the `gokrazy/kernel` and swap in the https://github.com/raspberrypi/linux kernel. You’ll need to modify it such that it includes all the modules you’ll want to use, as gokrazy does not use loadable kernel modules or an initrd.
* [ ] quite possibly, you might also need to adapt the device tree and device tree overlay files, as there are differences between upstream linux and the raspberry pi foundation’s kernel tree, IIRC

Hope that helps!

I’m closing this issue since supporting other devices is not something gokrazy is interested in currently.

**Comment by justbuchanan** [comment]
Thanks for all the info! I'll look into this a bit more and see what I can come up with. Based on the challenges you pointed out though, it looks like it may be more trouble than it's worth :/
